name: Build and Push Docker Image to Docker Hub

on:
    push:
        branches: ["main"]

jobs:
    docker:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Docker Hub Login
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Build Docker image
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-test-app:latest .

            - name: Push Docker image to Docker Hub
              run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-test-app:latest

            - name: Deploy to EC2
              uses: appleboy/ssh-action@v1.0.0
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                  docker pull ${{ secrets.DOCKER_USERNAME }}/flask-test-app:latest
                  docker stop flask-test-app || true
                  docker rm flask-test-app || true
                  docker run -d -p 80:5000 --name flask-test-app ${{ secrets.DOCKER_USERNAME }}/flask-test-app:latest

            